export default defineEventHandler(async (event) => {
  const data = [
    {
      id: 920,
      img: "/newimg/redcoat.png",
      title: "The north coat",
      shop: "VShop",
      productCode: "000920",
      quantity: 1,
      bbprice: 200,
      tmcprice: 60,
      newProduct: "N",
      productPercent: 95,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: true,
    },
    {
      id: 523,
      img: "/newimg/lvbag.png",
      title: "Gucci duffle bag",
      shop: "Dominmie",
      productCode: "00523",
      quantity: 23,
      bbprice: 960,
      tmcprice: 0,
      newProduct: "Y",
      productPercent: 100,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 22,
      img: "/newimg/cpucooler.png",
      title: "RGB liquid CPU Cooler",
      shop: "BarterGang",
      productCode: "00022",
      quantity: 17,
      bbprice: 0,
      tmcprice: 160,
      newProduct: "Y",
      productPercent: 100,
      discount: "Y",
      newPrice: 9,
      discountPercent: 96,
      favourite: false,
    },
    {
      id: 58,
      img: "/newimg/smallbooks.png",
      title: "Small BookSelf",
      shop: "BarterGang",
      productCode: "00058",
      quantity: 5,
      bbprice: 0,
      tmcprice: 300,
      newProduct: "Y",
      productPercent: 100,
      discount: "Y",
      newPrice: 69,
      discountPercent: 62,
      favourite: true,
    },
    {
      id: 922,
      img: "/img/ocs-0311581669927.jpg",
      title: "iPhone 11 Pro 64GB Gold",
      shop: "VShop",
      productCode: "000922",
      quantity: 1,
      bbprice: 30500,
      tmcprice: 0,
      newProduct: "N",
      productPercent: 100,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 921,
      img: "/img/ocs-2751581669816.jpg",
      title: "Samsung Tab S2 White TH",
      shop: "VShop",
      productCode: "000921",
      quantity: 1,
      bbprice: 4800,
      tmcprice: 0,
      newProduct: "N",
      productPercent: 95,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 919,
      img: "/img/ocs-5041581669559.jpg",
      title: "Samsung A80 Gold",
      shop: "VShop",
      productCode: "000919",
      quantity: 1,
      bbprice: 8200,
      tmcprice: 0,
      newProduct: "N",
      productPercent: 95,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 920,
      img: "/newimg/redcoat.png",
      title: "The north coat",
      shop: "VShop",
      productCode: "000920",
      quantity: 1,
      bbprice: 200,
      tmcprice: 60,
      newProduct: "N",
      productPercent: 95,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 861,
      img: "/newimg/dogfood.png",
      title: "Breed Dry Dog Food",
      shop: "BreedDry",
      productCode: "00861",
      quantity: 1,
      bbprice: 100,
      tmcprice: 0,
      newProduct: "N",
      productPercent: 99,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 115,
      img: "/img/img_2351519116522.jpg",
      title: "กระบอกน้ำสแตนเลส",
      shop: "BarterGang",
      productCode: "00115",
      quantity: 20,
      bbprice: 0,
      tmcprice: 790,
      newProduct: "Y",
      productPercent: 0,
      discount: "Y",
      newPrice: 99,
      discountPercent: 87,
      favourite: true,
    },
    {
      id: 143,
      img: "/img/img_5731520659036.jpg",
      title: "โคมไฟลูกโลกหินอัญมณีแกนหินอ่อนตั้งพื้น",
      shop: "BarterGang",
      productCode: "00143",
      quantity: 1,
      bbprice: 9900,
      tmcprice: 9900,
      newProduct: "N",
      productPercent: 95,
      discount: "Y",
      newPrice: 6500,
      discountPercent: 34,
      favourite: false,
    },
    {
      id: 190,
      img: "/img/flyster_skyhunter_x8_may_bay_f.jpg",
      title: "SKY Hunter X 8 Selfie Drone โดรนบังคับ",
      shop: "BarterGang",
      productCode: "00190",
      quantity: 1,
      bbprice: 1900,
      tmcprice: 0,
      newProduct: "Y",
      productPercent: 0,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: true,
    },
    {
      id: 386,
      img: "/img/40_751.jpg",
      title: "นาฬิกา BMW Motorsport ICE",
      shop: "BmwBarcelona",
      productCode: "00386",
      quantity: 1,
      bbprice: 6945,
      tmcprice: 0,
      newProduct: "Y",
      productPercent: 0,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: false,
    },
    {
      id: 410,
      img: "/img/61_020.jpg",
      title: "แบบรถจำลอง",
      shop: "BmwBarcelona",
      productCode: "00410",
      quantity: 1,
      bbprice: 0,
      tmcprice: 370,
      newProduct: "Y",
      productPercent: 0,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
      favourite: true,
    },
    {
      id: 475,
      img: "/img/ocs_5421564555034_537.jpg",
      title: "เสื้อเรย่อน คอวี มีกระเป๋า",
      shop: "PiggyGang",
      productCode: "00475",
      quantity: 1,
      bbprice: 150,
      tmcprice: 150,
      newProduct: "Y",
      productPercent: 0,
      discount: "Y",
      newPrice: 120,
      discountPercent: 20,
      favourite: false,
    },
    {
      id: 499,
      img: "/img/ocs-0821564559488.jpg",
      title: "เสื้อยืดแขนยาว",
      shop: "PiggyGang",
      productCode: "00499",
      quantity: 1,
      bbprice: 150,
      tmcprice: 150,
      newProduct: "Y",
      productPercent: 0,
      discount: "Y",
      newPrice: 120,
      discountPercent: 20,
      favourite: true,
    },
  ];
  return data;
});
