export default defineEventHandler(async (event) => {
  const data = [
    {
      id: 920,
      img: "~images/newimg/redcoat.png",
      title: "The north coat",
      shop: "VShop",
      productCode: "000920",
      quantity: 1,
      bbprice: 200,
      tmcprice: 60,
      newProduct: "N",
      productPercent: 95,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
    },
    {
      id: 523,
      img: "~images/newimg/lvbag.png",
      title: "Gucci duffle bag",
      shop: "Dominmie",
      productCode: "00523",
      quantity: 23,
      bbprice: 960,
      tmcprice: 0,
      newProduct: "Y",
      productPercent: 100,
      discount: "N",
      newPrice: 0,
      discountPercent: 0,
    },
    {
      id: 22,
      img: "~images/newimg/cpucooler.png",
      title: "RGB liquid CPU Cooler",
      shop: "BarterGang",
      productCode: "00022",
      quantity: 17,
      bbprice: 0,
      tmcprice: 160,
      newProduct: "Y",
      productPercent: 100,
      discount: "Y",
      newPrice: 9,
      discountPercent: 96,
    },
    {
      id: 58,
      img: "~images/newimg/smallbooks.png",
      title: "Small BookSelf",
      shop: "BarterGang",
      productCode: "00058",
      quantity: 5,
      bbprice: 0,
      tmcprice: 300,
      newProduct: "Y",
      productPercent: 100,
      discount: "Y",
      newPrice: 69,
      discountPercent: 62,
    },
  ];

  return data;
});
